from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Region:
    name: str
    source_url: str


REGIONS: tuple[Region, ...] = (
    # UK Nations & Crown Dependencies
    Region(
        "scotland",
        "https://download.geofabrik.de/europe/united-kingdom/scotland-latest-free.gpkg.zip",
    ),
    Region(
        "wales",
        "https://download.geofabrik.de/europe/united-kingdom/wales-latest-free.gpkg.zip",
    ),
    Region(
        "northern-ireland",
        "https://download.geofabrik.de/europe/ireland-and-northern-ireland-latest-free.gpkg.zip",
    ),
    Region(
        "isle-of-man",
        "https://download.geofabrik.de/europe/isle-of-man-latest-free.gpkg.zip",
    ),
    Region(
        "guernsey-jersey",
        "https://download.geofabrik.de/europe/guernsey-jersey-latest-free.gpkg.zip",
    ),
    # England Counties
    Region(
        "bedfordshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/bedfordshire-latest-free.gpkg.zip",
    ),
    Region(
        "berkshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/berkshire-latest-free.gpkg.zip",
    ),
    Region(
        "bristol",
        "https://download.geofabrik.de/europe/united-kingdom/england/bristol-latest-free.gpkg.zip",
    ),
    Region(
        "buckinghamshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/buckinghamshire-latest-free.gpkg.zip",
    ),
    Region(
        "cambridgeshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/cambridgeshire-latest-free.gpkg.zip",
    ),
    Region(
        "cheshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/cheshire-latest-free.gpkg.zip",
    ),
    Region(
        "cornwall",
        "https://download.geofabrik.de/europe/united-kingdom/england/cornwall-latest-free.gpkg.zip",
    ),
    Region(
        "cumbria",
        "https://download.geofabrik.de/europe/united-kingdom/england/cumbria-latest-free.gpkg.zip",
    ),
    Region(
        "derbyshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/derbyshire-latest-free.gpkg.zip",
    ),
    Region(
        "devon",
        "https://download.geofabrik.de/europe/united-kingdom/england/devon-latest-free.gpkg.zip",
    ),
    Region(
        "dorset",
        "https://download.geofabrik.de/europe/united-kingdom/england/dorset-latest-free.gpkg.zip",
    ),
    Region(
        "durham",
        "https://download.geofabrik.de/europe/united-kingdom/england/durham-latest-free.gpkg.zip",
    ),
    Region(
        "east-sussex",
        "https://download.geofabrik.de/europe/united-kingdom/england/east-sussex-latest-free.gpkg.zip",
    ),
    Region(
        "east-yorkshire-with-hull",
        "https://download.geofabrik.de/europe/united-kingdom/england/east-yorkshire-with-hull-latest-free.gpkg.zip",
    ),
    Region(
        "essex",
        "https://download.geofabrik.de/europe/united-kingdom/england/essex-latest-free.gpkg.zip",
    ),
    Region(
        "gloucestershire",
        "https://download.geofabrik.de/europe/united-kingdom/england/gloucestershire-latest-free.gpkg.zip",
    ),
    Region(
        "greater-london",
        "https://download.geofabrik.de/europe/united-kingdom/england/greater-london-latest-free.gpkg.zip",
    ),
    Region(
        "greater-manchester",
        "https://download.geofabrik.de/europe/united-kingdom/england/greater-manchester-latest-free.gpkg.zip",
    ),
    Region(
        "hampshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/hampshire-latest-free.gpkg.zip",
    ),
    Region(
        "herefordshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/herefordshire-latest-free.gpkg.zip",
    ),
    Region(
        "hertfordshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/hertfordshire-latest-free.gpkg.zip",
    ),
    Region(
        "isle-of-wight",
        "https://download.geofabrik.de/europe/united-kingdom/england/isle-of-wight-latest-free.gpkg.zip",
    ),
    Region(
        "kent",
        "https://download.geofabrik.de/europe/united-kingdom/england/kent-latest-free.gpkg.zip",
    ),
    Region(
        "lancashire",
        "https://download.geofabrik.de/europe/united-kingdom/england/lancashire-latest-free.gpkg.zip",
    ),
    Region(
        "leicestershire",
        "https://download.geofabrik.de/europe/united-kingdom/england/leicestershire-latest-free.gpkg.zip",
    ),
    Region(
        "lincolnshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/lincolnshire-latest-free.gpkg.zip",
    ),
    Region(
        "merseyside",
        "https://download.geofabrik.de/europe/united-kingdom/england/merseyside-latest-free.gpkg.zip",
    ),
    Region(
        "norfolk",
        "https://download.geofabrik.de/europe/united-kingdom/england/norfolk-latest-free.gpkg.zip",
    ),
    Region(
        "north-yorkshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/north-yorkshire-latest-free.gpkg.zip",
    ),
    Region(
        "northamptonshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/northamptonshire-latest-free.gpkg.zip",
    ),
    Region(
        "northumberland",
        "https://download.geofabrik.de/europe/united-kingdom/england/northumberland-latest-free.gpkg.zip",
    ),
    Region(
        "nottinghamshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/nottinghamshire-latest-free.gpkg.zip",
    ),
    Region(
        "oxfordshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/oxfordshire-latest-free.gpkg.zip",
    ),
    Region(
        "rutland",
        "https://download.geofabrik.de/europe/united-kingdom/england/rutland-latest-free.gpkg.zip",
    ),
    Region(
        "shropshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/shropshire-latest-free.gpkg.zip",
    ),
    Region(
        "somerset",
        "https://download.geofabrik.de/europe/united-kingdom/england/somerset-latest-free.gpkg.zip",
    ),
    Region(
        "south-yorkshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/south-yorkshire-latest-free.gpkg.zip",
    ),
    Region(
        "staffordshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/staffordshire-latest-free.gpkg.zip",
    ),
    Region(
        "suffolk",
        "https://download.geofabrik.de/europe/united-kingdom/england/suffolk-latest-free.gpkg.zip",
    ),
    Region(
        "surrey",
        "https://download.geofabrik.de/europe/united-kingdom/england/surrey-latest-free.gpkg.zip",
    ),
    Region(
        "tyne-and-wear",
        "https://download.geofabrik.de/europe/united-kingdom/england/tyne-and-wear-latest-free.gpkg.zip",
    ),
    Region(
        "warwickshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/warwickshire-latest-free.gpkg.zip",
    ),
    Region(
        "west-midlands",
        "https://download.geofabrik.de/europe/united-kingdom/england/west-midlands-latest-free.gpkg.zip",
    ),
    Region(
        "west-sussex",
        "https://download.geofabrik.de/europe/united-kingdom/england/west-sussex-latest-free.gpkg.zip",
    ),
    Region(
        "west-yorkshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/west-yorkshire-latest-free.gpkg.zip",
    ),
    Region(
        "wiltshire",
        "https://download.geofabrik.de/europe/united-kingdom/england/wiltshire-latest-free.gpkg.zip",
    ),
    Region(
        "worcestershire",
        "https://download.geofabrik.de/europe/united-kingdom/england/worcestershire-latest-free.gpkg.zip",
    ),
)


def get_region(name: str) -> Region:
    for region in REGIONS:
        if region.name == name:
            return region
    raise ValueError(f"Unknown region: {name}")
